# Generated by Django 5.0.1 on 2024-01-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=20)),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('single', 'single'), ('divorced', 'divorced'), ('other', 'other')], max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('education', models.CharField(choices=[('high school', 'high school'), ('degree', 'degree'), ('masters', 'masters'), ('other', 'other')], max_length=20)),
                ('digital_address', models.CharField(max_length=100)),
                ('country_from', models.CharField(max_length=100)),
                ('country_to', models.CharField(choices=[('canada', 'canada'), ('uae', 'uae'), ('australia', 'australia'), ('uk', 'uk'), ('germany', 'germany')], max_length=20)),
            ],
        ),
    ]
