# Generated by Django 5.0.1 on 2024-01-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='passport',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
